### ISSUE TITLE
question: can spelling issues be flagged as warnings/hints?

### ISSUE THREAD

**Issue by OliverNChalk** [davidmh/cspell.nvim#13]
Flagging spelling suggestions as errors seems a little dire. Is it possible to configure the level of diagnostic that cspell chooses to emit?

**Comment by davidmh** [comment]
You can, take a look at this option: https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md#diagnostics-postprocess

**Comment by quolpr** [comment]
@OliverNChalk hey! did you find the way how to make spelling as warning/hints?

**Comment by davidmh** [comment]
@quolpr the answer is in my last comment:

```lua
cspell.diagnostics.with({
  diagnostics_postprocess = function(diagnostic)
    diagnostic.severity =  vim.diagnostic.severity["WARN"]
  end
})
```

**Comment by quolpr** [comment]
@davidmh thank you so much! Yeah, I read your link, but it was not obvious to me because I am new to Lua. Thank you again 🙂

**Comment by xanderdunn** [comment]
For anyone confused on where this goes in your init.lua like I was:
```lua
null_ls.setup({
	sources = {
		cspell.diagnostics.with({
			-- info rather than errors
			diagnostics_postprocess = function(diagnostic)
				diagnostic.severity = vim.diagnostic.severity["INFO"]
			end,
		}),
	},
})

```
