### ISSUE TITLE
How do I add dictionaries to this?

### ISSUE THREAD

**Issue by jNaimXIII** [davidmh/cspell.nvim#14]
In VSCode, the Code Spell Checker extension seems to come bundled with a lot of dictionaries and marks far fewer words as errors than this extension. So, this isn't an extension-specific question but rather the CLI tool instead I guess.

VS Code
<img width="755" alt="image" src="https://github.com/davidmh/cspell.nvim/assets/115424698/ad0ef67f-807e-4cf5-8074-219ad72a3d5b">

NeoVim
<img width="1005" alt="image" src="https://github.com/davidmh/cspell.nvim/assets/115424698/9140a3d3-0901-4245-b8c5-f7a91465667c">

I faced this a while ago and [this somewhat solved my issue](https://blog.jannatinnaim.com/posts/automation/automate-tasks-even-if-you-might-do-them-only-once/) but, it's still not at parity with the VSCode one.

**Comment by fecet** [comment]
Could you please share your cspell.json or the install script mentioned in your blog?

**Comment by jNaimXIII** [comment]
> Could you please share your cspell.json or the install script mentioned in your blog?

Actually, you could just copy and paste the code blocks one after the another (except the first one, the rest go at the end of the main function). Here's the entire script.

```javascript
const { Octokit } = require("octokit");

const http = require("https");
const fs = require("fs");

const octokit = new Octokit({
  auth: "GITHUB_PERSONAL_ACCESS_TOKEN",
});

async function main() {
  const res = await octokit.rest.repos.getReadme({
    owner: "streetsidesoftware",
    repo: "cspell-dicts",
  });

  const remoteFile = fs.createWriteStream("README.md");
  http.get(res.data.download_url, function (response) {
    response.pipe(remoteFile);
  });

  const file = fs.readFileSync("README.md").toString();


  const lines = file.split("\n");

  const dictLines = lines.filter((line) => line.startsWith("| [@cspell/dict"));
  const dicts = dictLines.map((line) =>
    line.split("|")[1].split("]")[0].replace(" [", "")
  );

  // "@cspell/dict-ada/cspell-ext.json" -> "ada"
  const importLines = dicts
  .map((dict) =>
    dict.replace("@cspell/dict-", "").replace("/cspell-ext.json", "")
  )
  .map((dict) => `"${dict}"`)
  .join(",\n");

  // "@cspell/dict-ada/cspell-ext.json"
  // ->
  // npm install -g @cspell/dict-ada && cspell link add @cspell/dict-ada;
  let installLines = dicts.map(
    (dict) => `npm install -g ${dict} && cspell link add ${dict};`
  );
  installLines.unshift("#!/bin/bash");
  installLines = installLines.join("\n");

  fs.writeFileSync("install.sh", installLines);
  fs.writeFileSync("packages.txt", importLines);

  fs.rmSync("README.md");
}

main();
```

Please, read carefully what it does and only then run it. I won't be responsible for any harm caused by this. Thanks.

PS: I just hacked something together to make it work. Don't dig too much into it. 😅

**Comment by davidmh** [comment]
I feel like that's a bit too opinionated to include as part of the default plugin. I would be happy to include a link to your blog post in the README for whoever is interested.

**Comment by jNaimXIII** [comment]
Well, the issue is, it's still not at feature parity with the VSCode one. If you want you can link to it, sure. But, I'd like to know what else the VSCode one is doing to have all those other words marked as correct. Is it a custom dictionary or what?

**Comment by davidmh** [comment]
> it's still not at feature parity with the VSCode one.

I understand that, but parity with VSCode is not a goal for this plugin at the time.

> I'd like to know what else the VSCode one is doing to have all those other words marked as correct. Is it a custom dictionary or what?

I don't use VSCode, but I would love to learn that as well, perhaps you can ask on the [VSCode extension repo](https://github.com/streetsidesoftware/vscode-spell-checker)?

If you find something useful I would be open to work on an equivalent.

**Comment by davidmh** [comment]
Closing for now as parity with VSCode is not a goal at the moment.
