### ISSUE TITLE
Use yaml config file: cspell.config.yaml

### ISSUE THREAD

**Issue by undg** [davidmh/cspell.nvim#15]
This plugin doesn't support YAML version of the config. It is the second recommended option in [cspell documentation](https://cspell.org/docs/getting-started/). 

I found this file https://github.com/davidmh/cspell.nvim/blob/main/lua/cspell/helpers.lua#L6 and I hope it can be extended with YAML functionality. YAML is more readable and easier to maintain.

**Comment by davidmh** [comment]
That makes sense, I currently don't have the bandwidth to look into it, but I would be happy to provide some guidance to whoever wants to give it a try.

From the top of my head, here's a couple of things we would have to look into:

- Extend the source options to include the yaml file name
- Generalize the options `find_json`, `decode_json`, `encode_json` and all the internal references to be `find_config_file`, `decode_config_file`, etc. While keeping support for the exiting params.
- Find a recommended way to parse YML
  As far as I know, Neovim doesn't provide a YAML equivalent to `vim.json` to parse yml files without third party libraries/packages.
 That means that the YAML config file should only be supported if the user has defined all the `*_config_file` options, to ensure they're prepared to deal with YAML files.
 
 Happy to give more details as needed.

**Comment by eshepelyuk** [comment]
An additional option can be offloading `cspell` config manipulation, both json and yaml, to external tool, like [yq](https://github.com/mikefarah/yq).

**Comment by ievgenii-shepeliuk** [comment]
E.g. - working implementations of patching YAML file with `yq`
https://github.com/nvimtools/none-ls.nvim/blob/main/lua/null-ls/builtins/code_actions/regal.lua#L34-L58

**Comment by davidmh** [comment]
Closing for now, as is not on my plans to support yaml configuration files. But PRs are welcome.
