### ISSUE TITLE
Cpell fail to work when I specify the path to cspell.json

### ISSUE THREAD

**Issue by MKrbm** [davidmh/cspell.nvim#17]
OS : windows10
configs : I build my config on top of [NvChad](https://github.com/NvChad/NvChad)
cspell version : 7.0.0

```lua
local null_ls = require "null-ls"
local cwd = vim.fn.stdpath("config")
local CONFIG_PATH = vim.fn.expand(vim.fn.expand(cwd .. "/cspell/cspell.json"))
local cspell = require('cspell')

local shared_config = {
  find_json = function()
    return CONFIG_PATH
  end,
}

local sources = {
  cspell.diagnostics.with({
    config = shared_config
  }),
  cspell.code_actions.with({
    config = shared_config
  })
}
null_ls.setup {
  debug = true,
  sources = sources,
}
```

with `cspell.json` specified
![image](https://github.com/davidmh/cspell.nvim/assets/57752203/b592a632-47b9-498b-bfcb-9615e3d93263)

If I use
```lua
local sources = {
  cspell.diagnostics,
  cspell.code_actions,
}
```

Then, it starts to work. 
![image](https://github.com/davidmh/cspell.nvim/assets/57752203/93a7157d-d096-4f5d-bc62-be5721dd5a35)

Additionally, though i cannot reproduce the steps, I sometime encounter a serious bug where my treesitter freeze completely unless I stop to use cspell.diagnostics. 

And once treesitter start to freeze, I will somehow no longer use cspell even if I delete nvim-data folder and reinstall all plugins. 

Unfortunately my cspell.nvim stop working after taking the last screenshot and currently not available hahaha..

**Comment by davidmh** [comment]
Hi @MKrbm,

Thank you for reporting this issue, unfortunately, I don't have a windows machine to troubleshoot this.

As a complete shot in the dark, can you confirm that `CONFIG_PATH` is a valid windows path?

I believe windows uses backslashes instead of slashes, and I'm not sure if neovim manages that for you.

Just as a test, can you run:

```lua
print(vim.inspect(vim.json.decode(table.concat(vim.fn.readfile(CONFIG_PATH), ''))))
```

If it succeeds it means that's a real path.

Another option would be to add a `cspell.json` config file at the root of your project, then reference the real config using the `import` option: https://cspell.org/configuration/imports/

**Comment by MKrbm** [comment]
> ```lua
> print(vim.inspect(vim.json.decode(table.concat(vim.fn.readfile(CONFIG_PATH), ''))))

Yeah it correctly returns the content.
![image](https://github.com/davidmh/cspell.nvim/assets/57752203/e651a946-7fd8-4755-88bc-51c2447dd355)

Also, code_action works properly and can add to words field even when CONFIG_PATH is specified.



> Another option would be to add a cspell.json config file at the root of your project, then reference the real config using the import option: https://cspell.org/configuration/imports/

It sounds promising. I will give a try. But the potential problem is : do I need to create cspell.json everytime I change the directory? Indeed, I often change directory with `cd` command.

**Comment by davidmh** [comment]
> do I need to create cspell.json everytime I change the directory? Indeed, I often change directory with cd command.

I think I got tripped up by the base of the config path being `cwd`. I now see that you have a global config file.

In that case it may be easier to put the cspell.json file in one of the paths that CSpell looks at by default, like `~/cspell.json` and use the import there.

That way you can let cspell pick up the file config implicitly, without defining a `find_json` option in the plugin.

**Comment by MKrbm** [comment]
Okay. I'm currently out so I'm gonna try as soon as I back home.

**Comment by MKrbm** [comment]
It seems working! Thank you very much.
