### ISSUE TITLE
Feature Request: Add option to disable --language-id

### ISSUE THREAD

**Issue by kevintraver** [davidmh/cspell.nvim#21]
Add an option to disable passing the `--language-id` flag:

https://github.com/davidmh/cspell.nvim/blob/0e9c586bd7f7ab3f1f2f000a084121203e0ee62c/lua/cspell/diagnostics/init.lua#L42-L44

This flag overrides using adding additional dictionaries in cspell.json.

Related: https://github.com/davidmh/cspell.nvim/issues/20

**Comment by davidmh** [comment]
Sounds simple enough, but I don't fully understand the problem.

Would you mind expanding on the use case? 

It would also be easier to debug with a minimal configuration. You can take this file as an example: https://github.com/davidmh/cspell.nvim/blob/0e9c586bd7f7ab3f1f2f000a084121203e0ee62c/tests/minimal_init.lua

And you can add your own configuration right after this line:

https://github.com/davidmh/cspell.nvim/blob/0e9c586bd7f7ab3f1f2f000a084121203e0ee62c/tests/minimal_init.lua#L35

Something like:

```lua
    local null_ls = require("null-ls")
    local cspell = require("cspell")
    local sources = {
        cspell.diagnostics,
        cspell.code_actions,
    }

    null_ls.setup({ sources = sources })
```

Then you can start Neovim using that configuration as:

nvim -u minimal_init.lua some-other-file-to-lint.ts

**Comment by kevintraver** [comment]
Ah yes, looks like some of my dictionary links were actually broken in `~/.config/configstore/cspell.json`.

Once I got that fixed, it appears to be working as expected. So it was not an issue with `--language-id`.

Thanks for the the help.
