### ISSUE TITLE
Code actions with out null-ls

### ISSUE THREAD

**Issue by sajadspeed** [davidmh/cspell.nvim#23]
Hi, How can i use code actions with out `null-ls`?
I use `cmp` and `nvim-lint` for compilation and linting.

**Comment by davidmh** [comment]
Unfortunately, that's not possible at the moment. The code actions use null-ls as the LSP client, without it, we would have to come up with a stand alone client.

I know there are a few options out there to build generic language servers, but I haven't had the time to look into it.

**Comment by sajadspeed** [comment]
I found this one repository from you:
[cspell-nvim-minimal-init](https://github.com/davidmh/cspell-nvim-minimal-init/)
Does this not solve my problem? I want to have both code actions and diagnostics without null-ls.

**Comment by davidmh** [comment]
No, you can see I'm installing null-ls here: https://github.com/davidmh/cspell-nvim-minimal-init/blob/main/minimal-init.lua#L33-L48

**Comment by sajadspeed** [comment]
OK. Thanks a lot.

**Comment by quolpr** [comment]
I was able to make cspell-ls working on nvim, but the code looks somehow hacky + you need to modify extension and build locally

https://github.com/neovim/nvim-lspconfig/pull/1056#issuecomment-2192178087

But the great thing about that - you will not depend on none-ls + performance much better

**Comment by davidmh** [comment]
That's great @quolpr, do you think your changes to `vscode-spell-checker` can be upstreamed into the original repository?

I would definitely deprecate this plugin if we had a standalone LSP.

**Comment by quolpr** [comment]
Hey @davidmh!

I opened issue here https://github.com/streetsidesoftware/vscode-spell-checker/issues/3406 . I think cspell need native mode support, to avoid all hacks that I did. Let's see how discussion will go 🙂

**Comment by quolpr** [comment]
Finally! I was able to make lsp config without modifying cspell. Here is gist with instruction https://gist.github.com/quolpr/2d9560c0ad5e77796a068061c8ea439c

But still thinking about to add native mode to vscode-spell-checker
