### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by mcDevnagh** [davidmh/cspell.nvim#24]
[the README](https://github.com/davidmh/cspell.nvim/blob/0e9c586bd7f7ab3f1f2f000a084121203e0ee62c/README.md?plain=1#L58) says there are 2 functions in the config with the same name: `encode_json`.

Was one of them meant to be `decode_json`? See its usage [here](https://github.com/davidmh/cspell.nvim/blob/0e9c586bd7f7ab3f1f2f000a084121203e0ee62c/lua/cspell/helpers.lua#L108)

**Comment by davidmh** [comment]
Fixed in 335080b, thanks!
