### ISSUE TITLE
Migration to none-ls

### ISSUE THREAD

**Issue by eshepelyuk** [davidmh/cspell.nvim#29]
Hello

Since `null-ls` was archived and there is a backward compatible successor - `none-ls`
https://github.com/nvimtools/none-ls.nvim

Would it make sense to migrate this plugin to `none-ls` ?
With migration I mean fixing all links and references to point to`none-ls` repository.

The plugin itself is working in top of `none-ls` - I am currently using it.

**Comment by davidmh** [comment]
Oh that's cool!

Would you mind sending me a PR with it?

**Comment by eshepelyuk** [comment]
> Oh that's cool!
> 
> Would you mind sending me a PR with it?

will try and see how it goes

**Comment by eshepelyuk** [comment]
> Oh that's cool!
> 
> Would you mind sending me a PR with it?

Created #31

**Comment by eshepelyuk** [comment]
Hello @davidmh 

Maybe it also makes sense to modify "About" section, i.e. one on the right side.

![Screenshot_2023-11-17-21-27-36-328.jpeg](https://github.com/davidmh/cspell.nvim/assets/1279477/4df79133-fc5d-4ee4-98b7-436f1a85793e)
