### ISSUE TITLE
on_success handler example breaks cspell.json

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [davidmh/cspell.nvim#37]
Hello 

I was using this example to format my `cspell.json` on adding a new word.
```lua
on_success = function(cspell_config_file_path, params, action_name)
    if action_name == 'add_to_json' then
        os.execute(
            string.format(
                "cat %s | jq -S '.words |= sort' | tee %s > /dev/null",
                cspell_config_file_path,
                cspell_config_file_path
            )
        )
    end
end
```

And I've noticed a lot of issue when my `cspell.json` became broken, in particular it was becoming empty after some words additions. 
I've been playing with few different approaches and tools and came up with this handler that works fine for me, without any issues. It uses `yq` not `jq` for file manipulation.

```lua
local Job = require("plenary.job")
local cspell = require('cspell')
local cspell_config = {
    config = {
        on_success = function(cspell_config_file_path, params, action_name)
            if action_name == 'add_to_json' then
                Job:new({
                    command = "yq",
                    args = { "-P", "-i", "-oj", ".words|=sort()", cspell_config_file_path },
                    on_exit = function(j, return_val)
                        if return_val == 0 then return end
                        vim.notify(
                            "cspell.json format issue: " .. j:stderr_result()[1],
                            vim.log.levels.WARN,
                            { title = "cspell.nvim" }
                        )
                    end,
                }):start()
            end
        end
    },
}
```

**Comment by davidmh** [comment]
> And I've noticed a lot of issue when my cspell.json became broken, in particular it was becoming empty after some words additions.

Yeah, I noticed that as well, it has to do with jq not being able to process the same file piping the stdout. See: https://unix.stackexchange.com/a/722024

I was playing with the idea of breaking down the `on_success` callback into dedicated callbacks per code action: #38 

There I'm updating the example as: 

```lua
  ---@param payload AddToJSONSuccess
  on_add_to_json = function(payload)
      -- For example, you can format the cspell config file after you add a word
      os.execute(
          string.format(
              "jq -S '.words |= sort' %s > %s.tmp && mv %s.tmp %s",
              payload.cspell_config_path,
              payload.cspell_config_path,
              payload.cspell_config_path,
              payload.cspell_config_path
          )
      )
  end
```

I decided to keep using `jq` in the example because it feels like the go-to tool to manipulate JSON, and I've seen it being used in a lot of projects. But I'm open to using something else.

**Comment by ievgenii-shepeliuk** [comment]
Unlike `jq` whose author refuses to add inline file editing - `yq` allows to do this, so no need for piping. Also `yq` is not only for YAML but for JSON/XML/TOML etc.

**Comment by ievgenii-shepeliuk** [comment]
So, if you don't want to replace `jq` in documentation example - then please add a note, explaining that `jq` is unreliable and can cause `cspell.json` breaking.

**Comment by davidmh** [comment]
> add a note, explaining that `jq` is unreliable and can cause `cspell.json` breaking.

I wouldn't call `jq` unreliable, if anything it's just on me for not double checking that command worked properly.
