### ISSUE TITLE
Diagnostics of cspell is not displayed

### ISSUE THREAD

**Issue by oldqin97** [davidmh/cspell.nvim#39]
I set up cspell according to the documentation, but no diagnostics came out. I don’t know how to solve this problem.

<img width="607" alt="image" src="https://github.com/davidmh/cspell.nvim/assets/48620148/71fec3ff-5e5b-43d1-88c3-e93308db19f6">

**Comment by davidmh** [comment]
Hi @oldqin97 do you get any error messages? You can open the null-ls log with the command: `:NullLsLog`

Also, you should make sure the `cspell` cli is installed and available in your PATH, either through your shell session or through Mason.

**Comment by davidmh** [comment]
Closing for now, as it sounds like your neovim instance doesn't have access to cspell. Please reopen if that's not the case.
