### ISSUE TITLE
Asterisk suffix sometimes present on code actions options

### ISSUE THREAD

**Issue by GNRSN** [davidmh/cspell.nvim#47]
**Describe the bug**
As pictured, some completion results are followed by an asterisk which is then also inserted when that option is selected. On the picture I'm using lsp saga but the issue persists with others pickers including native `vim.lsp.buf.code_actions`

<img width="447" alt="Screenshot 2024-01-18 at 16 39 41" src="https://github.com/davidmh/cspell.nvim/assets/9020004/af49d231-d4af-4546-9080-e17695c582ed">

**To Reproduce**
I'm not passing any configuration options so this should be with default settings. The word "competion" produces this result consistently but I've seen a few other words do it as well, maybe 1 in 100?

Running from cspell-cli (`cspell-cli cspell lint`, result pictured) I can see that for "competion", both of the pictured options with asterisks are fix suggestions.

<img width="687" alt="image" src="https://github.com/davidmh/cspell.nvim/assets/9020004/172e8e73-3ec8-4908-af4c-b50caf8a1747">

Running with the the `--show-suggestions` flag gives us the asterisk, which I assume is meant to denote this as a recommended option?

<img width="966" alt="image" src="https://github.com/davidmh/cspell.nvim/assets/9020004/2074bef1-ee87-4fd0-b08c-ea2aec16ac18">

I think my question/suggestion is for cspell.nvim to strip the asterisks or find a way to call cspell which doesn't yield asterisks in suggestions.

**Comment by GNRSN** [comment]
Running the explicit suggestions command with --verbose flag shows that the denoted suggestions are part of common misspellings
![Uploading image.png…]()

**Comment by GNRSN** [comment]
And running with `--show-suggestions` and passing the output to the json reporter `--reporter @cspell/cspell-json-reporter` yields

```
        {
            "text": "competion",
           ...
            "suggestionsEx": [
                {
                    "word": "competition",
                    "isPreferred": true
                },
                {
                    "word": "completion",
                    "isPreferred": true
                },
                {
                    "word": "compton"
                },
                {
                    "word": "cooption"
                },
                {
                    "word": "commotion"
                }
            ],
            "suggestions": [
                "competition",
                "completion",
                "compton",
                "cooption",
                "commotion"
            ],
           ...
        },
```

**Comment by davidmh** [comment]
What a great timing! I just noticed this myself.

> strip the asterisks or find a way to call cspell which doesn't yield asterisks in suggestions.

That sounds like a good compromise. I'll look into the CSpell docs to make sure I understand why the asterisk is there in the first place, but if I can't figure out from the CSpell docs, then stripping it in the plugin sounds like a fine solution.

**Comment by GNRSN** [comment]
I would be interested in contributing on this but I'm still a bit of a lua and nvim esosystem novice, 

looking at how they are doing in the official vscode plugin, it seems as they're using the suggestions api to generate the code action when required. While as I understand it, we are "piggybacking" on the lint call where we're including suggestions in the output https://github.com/davidmh/cspell.nvim/blob/5112e55c70c5fac191d8a0ad2be5a131d19f9b4a/lua/cspell/diagnostics/init.lua#L42

It seems then as the "optimal" solution would be to rely on suggestions only when needed, especially if this would improve performance with code actions enabled. The output is nice and sorted by weight already.

<img width="403" alt="image" src="https://github.com/davidmh/cspell.nvim/assets/9020004/6c4237a8-de96-4c1f-a890-5a04c855b291">

One downside though is that it doesn't seem to support custom reporters like the lint command. 

I think it would be a benefit to avoid custom parsing all together by either using the json reporter or writing a custom reporter which returns only what we need. 

I fully understand and/or respect if that is out of scope for this fix or plugin though.

**Comment by davidmh** [comment]
> I think it would be a benefit to avoid custom parsing all together by either using the json reporter or writing a custom reporter which returns only what we need.

That would require an extra step for the enduser, to either install the custom reporter or at least have node support for the custom reporter.

I think you're right, running the command without the `--show-suggestions` param shows the two first results as fixes.

I would like to keep the suggestions though, because the fixes are truly just a guess, if the typo is bad enough, a suggestion may be a better fit.

I found a good compromise, but the fix depends partially on an upstream fix to none-ls. See: https://github.com/nvimtools/none-ls.nvim/pull/63

I'll push a fix for this issue soon.
