### ISSUE TITLE
Add neovim \ none- ls related topics to the repository.

### ISSUE THREAD

**Issue by eshepelyuk** [davidmh/cspell.nvim#48]
Hello

Due to changes [happening in none-ls codebase](https://github.com/nvimtools/none-ls.nvim/discussions/81)

And in [this thread](https://github.com/nvimtools/none-ls.nvim/discussions/81#discussioncomment-8612376)

Could you plz add topics to this repo for better discovery on github, e.g. like in new extras repo
https://github.com/nvimtools/none-ls-extras.nvim

![Screenshot_2024-02-28-04-07-41-663](https://github.com/davidmh/cspell.nvim/assets/1279477/119957b7-aa82-40c9-a56e-1161bc793475)

**Comment by davidmh** [comment]
Done

**Comment by eshepelyuk** [comment]
thanks
