### ISSUE TITLE
cspell on markdown files with none-ls

### ISSUE THREAD

**Issue by emko** [davidmh/cspell.nvim#49]
this works great with none-ls using typescript, rust etc but i can't figure out how to make it work with markdown files? is there a trick to it? i see the words highlighted red but when i try bring up none-ls it does not show up

thanks

**Comment by davidmh** [comment]
It's hard to say without seeing a specific example with your configuration.

Can you share both your config for this plugin and the cspell.json file you're using?

**Comment by davidmh** [comment]
@emko I'm guessing you found a solution to your problem? it may be worth posting the solution in case someone else runs into the same issue.
