### ISSUE TITLE
How is the recommended way of installing new languages? 

### ISSUE THREAD

**Issue by carlos-algms** [davidmh/cspell.nvim#50]
I've installed your plugin using Lazy
And `cspell` using Mason. 

I'm trying to add a new language dictionary, as I have projects that contain non-English content, and don't know how or where to install it.

**Comment by davidmh** [comment]
Hi Carlos,

> as I have projects that contain non-English content

You can start by creating a `cspell.json` file in your project. Then there's a couple of ways you can install non-english dictionaries, for example:

- Install a new language as an npm package.
   Looking for `@cspell/dict-de` gives you a few options for German dictionaries, then each version has instructions on how to define it in your `cspell.json` file, like this one: https://www.npmjs.com/package/@cspell/dict-de-de#manual-installation
   
- Use custom dictionaries: https://cspell.org/docs/dictionaries-custom/

All that is Neovim agnostic.
