### ISSUE TITLE
Severity Level

### ISSUE THREAD

**Issue by amoschristian** [davidmh/cspell.nvim#52]
Is there a way to change the severity level to Hint instead of Error by default?

![2024-04-25_18-50](https://github.com/davidmh/cspell.nvim/assets/46567795/49cb5e62-da4e-4aea-b755-866f5488dc8b)

**Comment by davidmh** [comment]
Yes, see this answer: https://github.com/davidmh/cspell.nvim/issues/13#issuecomment-1684086881

Just replace `WARN` with `HINT`.

**Comment by amoschristian** [comment]
@davidmh thank you so much, this is exactly what i need, cheers
