### ISSUE TITLE
Incorrect dictionary path when adding to dictionary 

### ISSUE THREAD

**Issue by mayromr** [davidmh/cspell.nvim#53]
**Describe the bug**
As specified by the [Cspell docs](https://cspell.org/docs/dictionaries-custom/), dictionaries should be relative to the cspell file but they are not treated as such when trying to add to dictionary.

**To Reproduce**
Set a `cspell.json` to an absulot path somewhere in your system with a relative dictionary path, then try to use the code action to add a word to that dictionary.

**Additional context**
The issue stems from [here](https://github.com/davidmh/cspell.nvim/blob/8c20fb6fbbf915473ac5e0958a1623dd991256b3/lua/cspell/code_actions/make_add_to_dictionary_action.lua#L30) `dictionary_path` should be be prepended with the cspell.json file path.

My current work around is:
```lua
      local spell_dir = vim.fn.stdpath 'config' .. '/spell'

      local config = {
        find_json = function()
          return spell_dir .. '/cspell.json'
        end,

        decode_json = function(content)
          local result = vim.json.decode(content)

          ---@diagnostic disable-next-line: undefined-field
          for _, entry in ipairs(result.dictionaryDefinitions) do
            entry.path = spell_dir .. '/' .. entry.path
          end

          return result
        end,
      }
```

**Comment by davidmh** [comment]
Hi @nhruo123, thanks for the report, makes sense. It should be solved by #55. Let me know if you run into any issues with the fix.
