### ISSUE TITLE
Fine Code Actions control

### ISSUE THREAD

**Issue by mayromr** [davidmh/cspell.nvim#54]
Hey :wave:, I use `cspell` in addition to other spell checker, and most of them share the same dictionary layout, when I want to mark a new word as good I allways add it to my dictionary and never to the `cspell.json` file.

A nice addition that could help out with my current workflow would a way to turn off the code action to add to the `cspell.json` file without turning off the rest of the code actions.

**Comment by davidmh** [comment]
Hi,

I see the value in the request, but it feels like an edge case and I would rather keep its complexity to a minimum, specially because I don't have a good idea on how useful this would be for other people.

I'll close this issue for now, but I'm open to PRs.
