### ISSUE TITLE
Add all words in current buffer to dictionary

### ISSUE THREAD

**Issue by sajadspeed** [davidmh/cspell.nvim#56]
Can I do this?

**Comment by davidmh** [comment]
Not with this plugin, but sounds like an achievable task using the CSpell cli, something like:

<img width="790" alt="Screenshot 2024-05-05 at 13 40 11" src="https://github.com/davidmh/cspell.nvim/assets/594302/2f7b7a00-52c6-4a96-9a80-3436c90690ba">

You could wrap everything in a user command or a custom mapping:

```lua
vim.api.nvim_create_user_command("AddAllWordsToDictionary", function()
  local cmd = "node_modules/.bin/cspell --words-only --no-summary --no-color --no-progress "
    .. vim.fn.expand("%")
    .. " | sort -u > /tmp/words.txt"
  vim.fn.system(cmd)
  vim.cmd("edit") -- trigger a refresh in the current buffer so none-ls can reanalyze the contents
end, { nargs = 0 })
```

You would have to customize the path to the CSpell cli and the target directory

**Comment by sajadspeed** [comment]
OK I got it... Thank you very much.
