### ISSUE TITLE
11276491721d34088f391cb188cac549df334afd breaks `~/` in dictionary path

### ISSUE THREAD

**Issue by Frederick888** [davidmh/cspell.nvim#58]
**Describe the bug**

My project-local `/path/to/project/.cspell.json` file is:
```json
{
  "language": "en-GB",
  "words": [ "..." ],
  "import": [
    "~\/.cSpell.json"
  ]
}
```

`~/.cSpell.json` is:

```json
{
  "language": "en-GB",
  "dictionaryDefinitions": [
    {
      "name": "Global",
      "path": "~/.vim/cSpell.txt",
      "addWords": true
    }
  ],
  "dictionaries": [
    "Global"
  ]
}
```

As cspell.nvim is not able to handle `import`, I customised the `decode_json` config to inject the Global dictionary: https://git.tsundere.moe/Frederick888/frederick-settings/-/blob/081cd1baac3baac12f1f64f475553399f6af6204/.config/nvim/lua/plugins/none-ls.lua#L100 (tl;dr it makes cspell.nvim think that the project-local config contains the Global dictionary definition.)

Since 11276491721d34088f391cb188cac549df334afd, when I tried to add a word to the global `~/.vim/cSpell.txt`, I started getting

```
cspell.nvim  ERROR Can't read /path/to/project/~/.vim/cSpell.txt
```

**To Reproduce**
Sorry I'm a bit short of time recently, but please let me know if a minimal reproducer is needed and I'll come back to it later 🙏 

**Additional context**

**Comment by algol2302** [comment]
Try to replace in your `~/.cSpell.json` file: `"path": "cSpell.txt"`. It helped me
