### ISSUE TITLE
`find_json` not working

### ISSUE THREAD

**Issue by mawkler** [davidmh/cspell.nvim#6]
I'm trying to use `find_json` to use a `cspell.json` inside `~/.config/cspell.json`, but can't get it to work.

**Steps to reproduce:**

1. Open a file in a directory that doesn't have a `cspell.json` anywhere in its path.
2. Trigger `vim.lsp.buf.code_action` on a spelling error and add the word
3. Neovim prints: `Created a new cspell.json file at /path/to/current/directory/cspell.json`

**Expected behaviour:**

Cspell would add the word to `~/.config/cspell.json`.

Here's the minimal config that I'm using:

<details>
<summary><b>Click to expand</b></summary>

```lua
local root = vim.fn.fnamemodify(vim.fn.expand('$HOME') .. '/code-other/nvim-test-config', ':p')

-- set stdpaths to use .repro
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ 'git', 'clone', '--filter=blob:none', 'https://github.com/folke/lazy.nvim.git', lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  { 'williamboman/mason.nvim', config = true },
  {
    'jose-elias-alvarez/null-ls.nvim',
    dependencies = { 'nvim-lua/plenary.nvim', 'davidmh/cspell.nvim' },
    event = 'VeryLazy',
    config = function()
      local null_ls = require('null-ls')
      local cspell = require('cspell')

      local cspell_config = vim.fn.expand('$HOME/.config/cspell.json')

      null_ls.setup({
        sources = {
          cspell.diagnostics,
          cspell.code_actions.with({
            config = {
              find_json = function() return cspell_config end,
            },
          }),
        }
      })
    end
  }
}

vim.keymap.set('n', '<C-q>', '<cmd>qa<CR>')
vim.keymap.set('n', '<space>a', vim.lsp.buf.code_action)

require('lazy').setup(plugins, {
  root = root .. '/plugins',
})
```

</details>

Here's the TL;DR of the config:

```lua
local null_ls = require('null-ls')
local cspell = require('cspell')

local cspell_config = vim.fn.expand('$HOME/.config/cspell.json')

null_ls.setup({
  sources = {
    cspell.diagnostics,
    cspell.code_actions.with({
      config = {
        find_json = function() return cspell_config end,
      },
    }),
  }
})
```

**Comment by davidmh** [comment]
Hi @mawkler, thank you for reporting this and including a minimal config; that helped a lot.

I was able to find the root cause of this issue. It looks like I'm passing the wrong set of params while I do the cache warm-up for the code actions within the diagnostics source.

The solution is to declare the same config for both sources:

```lua
local cspell_config = vim.fn.expand("$HOME/.config/cspell.json")
local shared_config = {
  find_json = function()
    return cspell_config
  end,
}

null_ls.setup({
  sources = {
    cspell.diagnostics.with({
      config = shared_config,
    }),
    cspell.code_actions.with({
      config = shared_config,
    }),
  },
})
```

Let me know if that fixes the problem for you. I'll keep the issue open until I update the documentation.

**Comment by davidmh** [comment]
I just merged an update to add that clarification to the [setup instructions](https://github.com/davidmh/cspell.nvim#configuration-options) and to add a small guard in case you forget to do it.

**Comment by mawkler** [comment]
Thank you, that works for me!
