### ISSUE TITLE
Diagnostics not resolved even after adding words to dictionary

### ISSUE THREAD

**Issue by rbhanot4739** [davidmh/cspell.nvim#69]
**Describe the bug**
I recently started using the plugin with LazyVim with the following configuration:
```
{
  {
    "nvimtools/none-ls.nvim",
    dependencies = {
      "mason.nvim",
      "nvimtools/none-ls-extras.nvim",
      "davidmh/cspell.nvim",
    },
    opts = function(_, opts)
      local cspell = require("cspell")
      local null_ls = require("null-ls")

      opts.sources = vim.list_extend(opts.sources or {}, {
        cspell.diagnostics,
        cspell.code_actions,
      })
    end,
  },
  {
    "williamboman/mason.nvim",
    opts = { ensure_installed = { "flake8", "mypy", "cspell" } },
  },
}

```

When I add the words to dictionary through the code actions, the file does gets created and words also get added to it however the diagnostics continue to show and do not resolve. I have tried putting the `cspell.json` in both cwd directory as well in `~/.config` but it does not seems to work.

Not sure if I am missing something here or not.

**To Reproduce**
1. Install LazyVim with default config(no extras or custom config).
2. Replace the `lua/plugins/example.lua` with above config .
3. Go to any spell diagnostic and trigger the code actions to create/add words to dictionary.

**Comment by davidmh** [comment]
Hi @rbhanot4739 can you check which version of cspell you're using?

As far as I know, mason doesn't allow you to install packages through the `ensure_installed` option, that seems to be an option only for `mason-lspconfig.nvim`, see: https://github.com/williamboman/mason.nvim/issues/1713 

So I'm guessing you're using an older version of cspell that might not support the features this plugin needs.

<img width="867" alt="Screenshot 2024-11-12 at 15 14 19" src="https://github.com/user-attachments/assets/592e9739-b4ff-4c56-8589-49d62578fdae">

**Comment by rbhanot4739** [comment]
@davidmh So the `cspell` binary seems to installed correctly for me with mason and the version is also the [latest](https://www.npmjs.com/package/cspell). 

```
❯ ls ~/.local/share/nvim/mason/packages/cspell/
 node_modules   mason-receipt.json   package-lock.json   package.json
❯ ~/.local/share/nvim/mason/bin/cspell --version
8.16.0
```
I am not sure what is the correct location for `cspell.json` because when I had the `cpsell.json` in the lsp root it wasn't working for me but when I moved it to git root it started to work ( yes the git_root and lsp_root are different for me).

So yeah, I was able work around this, although one nuance I noticed is that the words that I add to global dictionary in `~/.config/cpsell.json` do not seem to be picked. There can be lot of words which are common to lot of projects so ideally I would want to add those to a global dictionary rather project level dictionary for each project, so is there a way to make the extension look at union of both the files ?

**Comment by davidmh** [comment]
> is there a way to make the extension look at union of both the files ?

There is!

Check out this option: https://github.com/davidmh/cspell.nvim/blob/2c29bf573292c8f5053383d1be4ab908f4ecfc47/README.md?plain=1#L59-L64

I don't use it myself, but I gave it a try and it does seem to work as expected.

I'll close this issue for now, let me know how it goes.

**Comment by rbhanot4739** [comment]
@davidmh Yeah I was looking at this option and it seems to work correctly. Do you think this should be part of the default config ?
Also although not related to this issue, a nice feature to have would be  new option in the code actions popup "_**Add word to global dictionary**_", that can save the pain to manually add selected words to global dictionary.

**Comment by davidmh** [comment]
>  Do you think this should be part of the default config ?

Not sure, I would rather keep the opinions of this plugin at a minimum in order to reduce the complexity of the implementation.

>  a nice feature to have would be new option in the code actions popup "Add word to global dictionary", that can save the pain to manually add selected words to global dictionary.

That would also require checking if a global config exists, and defining where that global config should live. The CSpell package uses several patterns to define a config file, see: https://github.com/streetsidesoftware/cspell/blob/fa7f7f94d24619ee7656fced1b18489a8592bf6e/packages/cspell-lib/src/lib/Settings/Controller/configLoader/configLocations.ts#L11-L52

All that said, if you can think of a sensible default, I would be happy to review a PR.
