### ISSUE TITLE
Diagnostics don't work properly with cspell.json in cwd.

### ISSUE THREAD

**Issue by SeanSelene** [davidmh/cspell.nvim#70]
**Describe the bug**
Diagnostics always show `Unknown word` though I add the word to `./cspell.json`, but it works fine after I moved `cspell.json` to git respository, where the .git locate.

**Config**
```lua
  {
    "nvimtools/none-ls.nvim",
    dependencies = { "davidmh/cspell.nvim" },
    opts = function(_, opts)
      local cspell = require("cspell")
      opts.sources = vim.list_extend(opts.sources or {}, {
        cspell.diagnostics.with({
          diagnostics_postprocess = function(diagnostic)
            diagnostic.severity = vim.diagnostic.severity.HINT
          end,
        }),
        cspell.code_actions,
      })
    end,
  },
```

**Version**
8.16.0 (The latest so far)

**To Reproduce**
1. Init a git repository, create a subdirectory and cd to the dir
2. Create a file and write an unknown word
3. Add the word to `./cspell.json` via code action.
4. Diagnostics still shows `Unkonwn word`
5. Move `spell.json` to git rep.
6. Diagnostics disappeared.

**Comment by davidmh** [comment]
Hi @road2coder, yeah, I see the issue. I'll look into it in the next few days.

**Comment by davidmh** [comment]
Found a quick fix, checkout the latest commit and let me know if that does it for your.

For some extra context, I'm using the same root as the none-ls client to choose the path for the new cspell.json file, which means the config file will get added to the git root.

**Comment by SeanSelene** [comment]
> checkout the latest commit and let me know if that does it for your.

Hi, @davidmh. I've checked out [be04e473](https://github.com/davidmh/cspell.nvim/commit/be04e47348c04f89614d99cf73a7ce1165a2e3ec), diagnostics still do not work well while code actions do. 

> For some extra context, I'm using the same root as the none-ls client to choose the path for the new cspell.json file, which means the config file will get added to the git root

Yeah, the problem only exists when the cwd is not the git root.

**Comment by davidmh** [comment]
Hey @road2coder,

I can reproduce the issue anymore, I ran the scenario you describe using a minimal configuration and things work as expected:

https://asciinema.org/a/dL3ofk0JFIuzBNMmbasjX3dyN

Could you check again, and if it still fails, could you post your full nvim config?

**Comment by road2coder** [comment]
> https://asciinema.org/a/dL3ofk0JFIuzBNMmbasjX3dyN

**Comment by SeanSelene** [comment]
Hello, @davidmh .
> https://asciinema.org/a/dL3ofk0JFIuzBNMmbasjX3dyN

I have watched the video and noticed that your cspell.json locates in the git root. Things actually work as expected in this scenario but my cspell.json locates in the sub dir which because there is an action `Add "xxx" to the subdir` in the earlier commit but not in the current commit. So, everything goes fine now.
